### ISSUE TITLE
Lien dysfonctionnel manuel MAGNARD

### ISSUE THREAD

**Issue by Petule-git** [eyssette/ressources-generales-enseignement-philosophie#1]
Bonjour,
Tout d'abord merci beaucoup de nous partager autant de resources qui me sont utiles.
J'aurais aimé pourvoir consulter les manuels de chez MAGNARD mais vos liens ne fonctionnent plus.
Merci
Bonne journée

**Comment by eyssette** [comment]
J'ai mis les nouveaux liens. Merci d'avoir repérer ce souci !
